In [7]:
import numpy as np 
import tensorflow as tf 


#### tensorflow


In [4]:
print(tf.executing_eagerly())

True


In [9]:
a = 1 
b = 2 
c = tf.math.add(a, b)
print(c)
print(f"c type {type(c)}")

tf.Tensor(3, shape=(), dtype=int32)
c type <class 'tensorflow.python.framework.ops.EagerTensor'>


In [10]:
c.numpy()

3

#### tensorflow Scalar 
1. Scalar
    - scalar는 정수나 실수와 같은 상수(Constant Number)를 나타낸다. 
    - 양을 나타내지만 방향성을 갖지는 않는다. 따라서 차수가 0인 된다. 
    - tensorflow에서는 rank-0 tensor이라고 한다. 

In [12]:
a = tf.constant(1)
b = tf.constant(2)
print("a", a)
print("b", b)

a tf.Tensor(1, shape=(), dtype=int32)
b tf.Tensor(2, shape=(), dtype=int32)


#### rank() 함수를 사용하면 tensor 객체의 차수를 알 수 있다. 

In [13]:
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


#### cast() 함수를 사용하면 tensor의 datatype을 반환한다. 

In [16]:
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [19]:
add_c = tf.math.add(a, b)
sub_c = tf.math.subtract(a, b)
mul_c = tf.math.multiply(a, b)
div_c = tf.math.divide(a, b)
mod_c = tf.math.mod(a, b)
rem_c = tf.math.floordiv(a, b)

print(add_c)
print(sub_c)
print(mul_c)
print(div_c)
print(mod_c)
print(rem_c)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(-1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(0.5, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


#### tensorflow Vector  


1.   Vector 
    * vector는 여러 개의 scalar 값을 원소로 갖는 1차원 배열로 표현된다. 
    * scalar 여러 개가 동일한 축 방향으로 나열된 개념이다.  
    * 좌표계 공간으로 표현하면 어떤 방향으로 크기를 갖는다. 따라서 원소값의 크기 뿐만 아니라 원소들이 나열되는 순서도 의미가 있다. 

In [23]:
py_list = [10., 20., 30. ]
np_arr = np.array(py_list)

vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(np_arr, dtype=tf.float32)

print("vec1", vec1)
print("vec2", vec2)
print(tf.rank(vec1))
print(tf.rank(vec2))


vec1 tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2 tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
result tf.Tensor([20. 40. 60.], shape=(3,), dtype=float32)
rank tf.Tensor(1, shape=(), dtype=int32)


In [24]:
add1 = tf.math.add(vec1, vec2)
print("result", add1)
print("rank", tf.rank(add1))

result tf.Tensor([20. 40. 60.], shape=(3,), dtype=float32)
rank tf.Tensor(1, shape=(), dtype=int32)


In [25]:
add2 = vec1 + vec2
print("result", add2)
print("rank", tf.rank(add2))

result tf.Tensor([20. 40. 60.], shape=(3,), dtype=float32)
rank tf.Tensor(1, shape=(), dtype=int32)


In [26]:
print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))


tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(60.0, shape=(), dtype=float32)


In [27]:
print(tf.math.square(vec1))
print(tf.math.square(vec2))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)
tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


#### tensorflow Matrix  

1.   matrix 
    * matrix는 차수가 1인 vector를 같은 축 방향으로 나열하는 개념이다. 
    * 여러 개의 1차원 vector를 원소로 갖는 1차원 배열이다. 
    * 원소의 차수가 1이므로 차수가 2가 된다. 
    * tensorflow에서는 rank-2 tensor이라고 한다. 

In [29]:
mat_list = [[10, 20], [30, 40]]
mat1 = tf.constant(mat_list)
print("mat1", mat1)
print(tf.rank(mat1))

mat1 tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [30]:
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

mat2 = tf.stack([vec1, vec2])
print(mat2)

tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


#### tensorflow Tensor 
1.   tensor 


In [31]:
mat1 = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]

mat2 = [[9, 10, 11, 12], 
        [13, 14, 15, 16]]
        
mat3 = [[17, 18, 19, 20], 
        [21, 22, 23, 24]]

ten1 = tf.constant([mat1, mat2, mat3])
print(ten1)
print(tf.rank(ten1))

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [32]:
ten2 = tf.stack([mat1, mat2, mat3])
print(ten2)
print(tf.rank(ten2))

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
