#### tensorflow indexing 

In [1]:
import numpy as np 
import tensorflow as tf 

In [4]:
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)
print(vec[-1])
print(vec[:3])


tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [9]:
mat = tf.constant([[10, 20, 30],[40, 50, 60]])
print(mat)
print(mat[0, 2])
print(mat[0, :])
print(mat[:, 1])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([20 50], shape=(2,), dtype=int32)


In [15]:
ten = tf.constant([
                   [[10, 20, 30],
                    [40, 50, 60]], 
                  [[-10, -20, -30], 
                   [40, 50, 60]]])
print(ten)
print(ten[0, :, :])
print(ten[:, :2, :2])

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [ 40  50  60]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [ 40  50]]], shape=(2, 2, 2), dtype=int32)
