#### tensorflow reshape 

In [1]:
import tensorflow as tf 
import numpy as np 

In [5]:
ten1 = tf.constant(range(0, 24))
print(ten1)

ten2 = tf.reshape(ten1, [3, 8])
print(ten2)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [6]:
ten3 = tf.reshape(ten1, [-1, 4])
print(ten3)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [7]:
ten4 = tf.reshape(ten3, [-1])
print(ten4)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [8]:
ten5 = tf.reshape(ten4, [-1, 3, 4])
print(ten5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
