In [1]:
import numpy as np 
import tensorflow as tf 

tensorflow variable 



In [3]:
ten1 = tf.constant([[0, 1, 2],
                  [3, 4, 5]])
print(ten1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [5]:
ten_var1 = tf.Variable(ten1)
print(ten_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>


In [6]:
print(f"Name : {ten_var1.name}")
print(f"Shape : {ten_var1.shape}")
print(f"data type : {ten_var1.dtype}")
print(f"array : {ten_var1.numpy()}")

Name : Variable:0
Shape : (2, 3)
data type : <dtype: 'int32'>
array : [[0 1 2]
 [3 4 5]]


In [9]:
ten_var1.assign([[1, 1, 1],
                 [2, 2, 2]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>

In [7]:
print(f"Name : {ten_var1.name}")
print(f"Shape : {ten_var1.shape}")
print(f"data type : {ten_var1.dtype}")
print(f"array : {ten_var1.numpy()}")

Name : Variable:0
Shape : (2, 3)
data type : <dtype: 'int32'>
array : [[0 1 2]
 [3 4 5]]
