#### user defined 

In [1]:
import os 
import sys 
import cv2 
import numpy as np 
import pandas as pd 
import tensorflow as tf 
import albumentations as at  
import matplotlib.pyplot as plt

In [2]:
from IPython.display import SVG
from tensorflow.keras.datasets import mnist 
from sklearn.model_selection import train_test_split 
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.layers import Activation, Dense, Input, Flatten, Dropout 
from tensorflow.keras.utils import to_categorical, Sequence, model_to_dot, plot_model

#### user defined loss function 
* tensorflow에서 기본으로 제공하는 loss function 외에 사용자가 직접 정의한 손실함수를 정의 모델 훈련이 가능하다. 

In [15]:
# sample data 
#x = np.arange(0.0, 6.0, 1.0)
#y = np.arange(2.0, 14.0, 2.0)
x = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
y = np.array([2.0, 4.0, 6.0, 8.0, 10.0, 12.0], dtype=float)


In [7]:
model = Sequential([Dense(units=1, input_shape=[1])])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [18]:
def custom_huber_loss(y_true, y_pred):
    threshold = 1
    error = y_true - y_pred 

    small = tf.abs(error) <= threshold
    
    #12 loss 
    small_error = tf.square(error)/2

    #11 loss 
    big_error = threshold * (tf.abs(error)-(threshold/2))

    return tf.where(small, small_error, big_error)

In [19]:
model.compile(optimizer="sgd", loss=custom_huber_loss)
model.fit(x, y, epochs=1000, verbose=0)

print(model.predict([6.0]))

[[14.050795]]


In [24]:
c1 = tf.constant([1, 1])
c2 = tf.constant([2, 2])
c3 = tf.constant([0, 3])
cond = tf.constant([True, False])
print(c1)
print(c2)
print(c3)
print(cond)

c1.numpy()
print(c1.numpy)


tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor([ True False], shape=(2,), dtype=bool)
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>>


In [25]:
def get_print(input):
    print(input.numpy())

In [30]:
get_print(tf.where(cond, c1, c2))
get_print(tf.where(tf.less(c1, c2), c1, c2))
get_print(tf.where(tf.greater(c2, c3), c2, c3))


[1 2]
[1 1]
[2 3]


In [32]:
c4 = tf.constant([[1], [2], [3]])
c5 = tf.constant([[1, 2, 3, 4]])
print(c4)
print(c5)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


In [34]:
get_print(tf.where(tf.less(c4, c5), tf.multiply(c4, c5), tf.multiply(c5, -1)))

[[-1  2  3  4]
 [-1 -2  6  8]
 [-1 -2 -3 12]]
